basePath: /
definitions:
  ErrorDetail:
    additionalProperties:
      type: string
    type: object
  Failure-ErrorDetail:
    properties:
      code:
        type: integer
      error:
        $ref: '#/definitions/ErrorDetail'
    type: object
  Failure-string:
    properties:
      code:
        type: integer
      error:
        type: string
    type: object
  SignInRequest:
    properties:
      password:
        maxLength: 128
        minLength: 8
        type: string
      username:
        maxLength: 16
        minLength: 4
        type: string
    required:
    - password
    - username
    type: object
  SignInResponse:
    properties:
      token:
        type: string
    type: object
  SignUpRequest:
    properties:
      password:
        maxLength: 128
        minLength: 8
        type: string
      username:
        maxLength: 16
        minLength: 4
        type: string
    required:
    - password
    - username
    type: object
  SignUpResponse:
    properties:
      id:
        example: b8ae9666-23b8-4ffb-8cf1-f7df0d02130a
        type: string
    type: object
  Success-SignInResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/SignInResponse'
    type: object
  Success-SignUpResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/SignUpResponse'
    type: object
info:
  contact: {}
  description: This is api for upside application
  title: Upside API
  version: "1.0"
paths:
  /auth/_sign-in:
    post:
      consumes:
      - application/json
      parameters:
      - description: Request body for sign in
        in: body
        name: SignInRequest
        required: true
        schema:
          $ref: '#/definitions/SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Success-SignInResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Failure-ErrorDetail'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/Failure-string'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Failure-string'
      summary: Sign in
      tags:
      - Accounts
  /auth/_sign-up:
    post:
      consumes:
      - application/json
      parameters:
      - description: Request body for sign up
        in: body
        name: SignUpRequest
        required: true
        schema:
          $ref: '#/definitions/SignUpRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/Success-SignUpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Failure-ErrorDetail'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Failure-string'
      summary: Sign up
      tags:
      - Accounts
swagger: "2.0"
