basePath: /
definitions:
  dto.SignUpRequest:
    properties:
      password:
        maxLength: 128
        minLength: 8
        type: string
      username:
        maxLength: 16
        minLength: 4
        type: string
    required:
    - password
    - username
    type: object
  dto.SignUpResponse:
    properties:
      id:
        type: string
    type: object
  handler.SuccessWithData:
    properties:
      code:
        example: 201
        type: integer
      data: {}
      message:
        example: created
        type: string
    type: object
info:
  contact: {}
  description: This is api for upside application
  title: Upside API
  version: "1.0"
paths:
  /auth/_sign-up:
    post:
      consumes:
      - application/json
      parameters:
      - description: Request body for sign up
        in: body
        name: SignUpRequest
        required: true
        schema:
          $ref: '#/definitions/dto.SignUpRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/handler.SuccessWithData'
            - properties:
                data:
                  $ref: '#/definitions/dto.SignUpResponse'
              type: object
      summary: Sign up
      tags:
      - accounts
swagger: "2.0"
